# Generated by Django 3.2 on 2021-05-31 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210531_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 16, 35, 23, 594964)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 16, 35, 23, 516006)),
        ),
    ]
