# Generated by Django 3.2 on 2021-05-31 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210531_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 17, 3, 40, 404969)),
        ),
        migrations.AlterField(
            model_name='article',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='blog.user'),
        ),
        migrations.AlterField(
            model_name='details',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdet', to='blog.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 17, 3, 40, 271045)),
        ),
    ]
