# Generated by Django 3.2 on 2021-05-31 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210531_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 881411)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 9, 56, 787972)),
        ),
    ]
